export interface IProduct {
  id: string
  images: string[]
  tags: string[]
  title: string
  price: number
  description: string
  colors: string[]
  sizes: string[]
  slug: string
  gender: "MEN" | "WOMEN"
  category:
    | "MEN_TSHIRT"
    | "MEN_TANK"
    | "MEN_HOODIE"
    | "MEN_SWEATSHIRT"
    | "MEN_JOGGERS"
    | "MEN_SHORTS"
    | "MEN_COMPRESSION"
    | "MEN_LEGGINGS"
    | "MEN_OUTERWEAR"
    | "MEN_SEAMLESS"
    | "MEN_OVERSIZE"
    | "MEN_TRAINING"
    | "MEN_RUNNING"
    | "MEN_POWERLIFTING"
    | "MEN_CROSSFIT"
    | "MEN_RECOVERY"
    | "WOMEN_SPORT_BRA"
    | "WOMEN_TSHIRT"
    | "WOMEN_TANK"
    | "WOMEN_HOODIE"
    | "WOMEN_CROP"
    | "WOMEN_LEGGINGS"
    | "WOMEN_SHORTS"
    | "WOMEN_SEAMLESS"
    | "WOMEN_HIGHWAIST"
    | "WOMEN_GYM_SET"
    | "WOMEN_RUNNING"
    | "WOMEN_YOGA"
    | "WOMEN_COMPRESSION"
    | "WOMEN_RECOVERY"
    | "ACC_BAG"
    | "ACC_GLOVES"
    | "ACC_STRAPS"
    | "ACC_WRAPS"
    | "ACC_BELT"
    | "ACC_SHAKER"
    | "ACC_BOTTLE"
    | "ACC_CAP"
    | "ACC_BEANIE"
    | "ACC_TOWEL"
    | "ACC_WATCH"
    | "ACC_SOCKS"
    | "ACC_KNEE_SLEEVES"
    | "ACC_WRIST_SLEEVES"
    | "ACC_BACKPACK"
    | "ACC_GYM_ESSENTIAL"
    | "NUT_PROTEIN"
    | "NUT_WHEY"
    | "NUT_ISOLATE"
    | "NUT_CASEIN"
    | "NUT_BCAA"
    | "NUT_EAA"
    | "NUT_PREWORKOUT"
    | "NUT_FATBURNER"
    | "NUT_VITAMINS"
    | "NUT_TESTOSTERONE"
    | "NUT_CREATINE"
    | "NUT_ENERGY"
    | "NUT_RECOVERY"
    | "NUT_WEIGHT_GAINER"
    | "NUT_SHRED"
    | "NUT_HEALTH"
    | "NUT_SUPPLEMENT"

  material?: string
  fit?: string
  care?: string
  origin?: string
}
